---

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: 0440

- name:  Run the Composer installer
  command: creates="/usr/local/bin/composer" php /tmp/composer-setup.php --install-dir=/usr/local/bin/ --filename=composer 

- name: Create writeable ~/.composer
  become: false
  file:
    path: ~/.composer
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ apache_group }}"
    mode: 0770
    recurse: yes

- name: Create writeable ~/.drush
  become: false
  file:
    path: ~/.drush
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ apache_group }}"
    mode: 0770
    recurse: yes    